services:
    neko:
        image: "dockette/neko:chromium"
        restart: "unless-stopped"
        shm_size: "2gb"
        cap_add:
            - SYS_ADMIN
        ports:
            - "8080:8080" # neko desktop
            - "19222:19222" # cdp
            - "8931:8931" # playwright-mcp
            - "56000-56100:56000-56100/udp"
        volumes:
            - ".docker/chrome:/home/neko/.config/chromium"
        environment:
            NEKO_DESKTOP_SCREEN: 1920x1080@30
            NEKO_WEBRTC_EPR: 56000-56100
            NEKO_WEBRTC_NAT1TO1: 127.0.0.1
            NEKO_WEBRTC_ICELITE: 1
            NEKO_DESKTOP_UNMINIMIZE: true
            NEKO_DESKTOP_UPLOAD_DROP: true
            NEKO_MEMBER_PROVIDER: "noauth"
            NEKO_CHROME_FLAGS: "--load-extension=/srv/mcp/chrome-mcp/extension,/srv/mcp/playwright-mcp/extension"
